import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { AccessPerformanceAdjudicationService } from '../src/domain.mjs';
import { AtomicStore } from '../src/store.mjs';

class MemoryStore { constructor() { this.database = { accessPerformanceAdjudicationReviews: [] }; this.writes = 0; } read() { return structuredClone(this.database); } write(data) { this.database = structuredClone(data); this.writes += 1; } }
const owner = { id: 'owner-857', role: 'evidence_owner' };
const input = { supplierId: 'SUP-857', evidenceReference: 'EVD-857', adjudicationReference: 'ADJ-857-ACCESS-01', adjudicationScope: 'access_entitlement_adjudication' };
const chain = [{ action: 'profileAdjudication', role: 'adjudication_profile_analyst' }, { action: 'verifyFinalization', role: 'adjudication_finalization_verifier' }, { action: 'validateCommitment', role: 'adjudication_commitment_validator' }, { action: 'approveAdjudication', role: 'adjudication_authority' }, { action: 'resolveAdjudication', role: 'adjudication_registrar' }];

describe('AccessPerformanceAdjudicationService', () => {
  it('records the complete independently controlled adjudication lifecycle', () => { const store = new MemoryStore(); const service = new AccessPerformanceAdjudicationService(store); let record = service.submit(input, owner, 'request-submit-857'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `request-${step.action}-857`); expect(record.status).toBe('adjudication_resolved'); expect(record.events.map((event) => event.type)).toContain('adjudication_resolved'); expect(store.writes).toBe(6); });
  it('rejects invalid input and invalid role or order without mutation', () => { const store = new MemoryStore(); const service = new AccessPerformanceAdjudicationService(store); expect(() => service.submit({ ...input, adjudicationScope: 'other' }, owner, 'request-invalid-857')).toThrow('adjudication scope is invalid'); const record = service.submit(input, owner, 'request-state-857'); expect(() => service.transition(record.id, 'profileAdjudication', { note: 'attempt' }, owner, 'request-role-857')).toThrow('role adjudication_profile_analyst is required'); expect(() => service.transition(record.id, 'validateCommitment', { note: 'order' }, { id: 'validator', role: 'adjudication_commitment_validator' }, 'request-order-857')).toThrow('access-performance adjudication review must be finalization_verified'); expect(store.writes).toBe(1); });
  it('rejects duplicate requests, missing records, and terminal transitions', () => { const store = new MemoryStore(); const service = new AccessPerformanceAdjudicationService(store); let record = service.submit(input, owner, 'request-repeat-857'); expect(() => service.transition(record.id, 'profileAdjudication', { note: 'repeat' }, { id: 'profile', role: 'adjudication_profile_analyst' }, 'request-repeat-857')).toThrow('request identifier was already used'); expect(() => service.get('missing-857')).toThrow('access-performance adjudication review was not found'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `terminal-${step.action}-857`); expect(() => service.transition(record.id, 'resolveAdjudication', { note: 'retry' }, { id: 'registrar', role: 'adjudication_registrar' }, 'retry-resolution-857')).toThrow('access-performance adjudication review must be adjudication_approved'); });
  it('recovers an absent adjudication data file', () => { const directory = mkdtempSync(join(tmpdir(), 'access-performance-adjudication-')); try { const store = new AtomicStore(join(directory, 'data', 'access-performance-adjudication-reviews.json')); expect(store.read()).toEqual({ accessPerformanceAdjudicationReviews: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
